<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>TheConcernedCat.ConcernedCartographer</RootNamespace>
    <AssemblyName>TheConcernedCat.ConcernedCartographer</AssemblyName>
    <Version>0.3.0</Version>
    <FileAlignment>512</FileAlignment>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JotunnLib" Version="2.29.2" />
  </ItemGroup>
</Project>
